DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

TRAIN:
  EARLY_STOPPING: True
  EARLY_STOPPING_PATIENCE: 10
  PRINT_FREQ: 9999

TEST:
  FINAL_MODEL: "best_val"

OPTIM:
  NAME: "adamw"
  LR: 0.0005
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  WARMUP_TYPE: "linear"
  WARMUP_CONS_LR: 1e-4

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"